export default [
  {
    bg: '#A8DDE9',
    color: '#3F5B98',
    screen: 'Movie',
    title: 'Animated Carousel',
    subTitle: 'We will learn about how to..',
    descriptions: [
      '- use the snapToInterval',
      '- animate FlatList items',
      '- create the backdrop',
      '- add LinearGradient',
    ],
  },

  {
    bg: '#086E4B',
    color: '#FCBE4A',
    screen: 'Words',
    title: 'Animated Sentence',
    subTitle: 'We will learn about how to..',
    descriptions: [
      '- animate words in a sentence',
      "- use 'Animated.timing'",
      "- use 'Animated.stagger'",
    ],

    subCategories: [
      'Fruits & Vegetables',
      'Frozen Food',
      'Bakery',
      'Snacks & Desserts',
      'Beverages',
      'Alcoholic beverages',
      'Noodles & Pasta',
      'Rice & Cooking oil',
    ],
  },
  // {
  //   bg: '#FECBCA',
  //   color: '#FD5963',
  //   category: 'Beauty',
  //   subCategories: ['Skincare', 'Makeup', 'Nail care', 'Perfume'],
  // },
  // {
  //   bg: '#193B8C',
  //   color: '#FECBCD',
  //   category: 'Baby & Kids',
  //   subCategories: [
  //     'Toys',
  //     'Trolleys',
  //     'LEGO®',
  //     'Electronics',
  //     'Puzzles',
  //     'Costumes',
  //     'Food',
  //     'Hygiene & Care',
  //     "Child's room",
  //     'Feeding accessories',
  //   ],
  // },
  // {
  //   bg: '#FDBD50',
  //   color: '#F5F5EB',
  //   category: 'Homeware',
  //   subCategories: [
  //     'Air purifiers',
  //     'Stoves, hoods & ovens',
  //     'Refrigerators',
  //     'Coffee & Tea',
  //     'Air conditioning',
  //     'Grilling',
  //     'Vacuum cleaners',
  //   ],
  // },
];
